services:
    api:
        container_name: dev_api
        ports: 
        - 3000:3000
        environment: 
        - PGUSER=morris
        - PGHOST=db
        - PGPASSWORD=password
        - PGDATABASE=database
        - PGPORT=5432
        - NODE_ENV=development
        - SECRET=my_token_super_secret_password
        depends_on:
        - db
        command: bash -c "npm install && npm run seedDev && npm run dev"
    db:
        container_name: dev_db
        volumes:
        - "db:/var/lib/postgresql/data"
        environment: 
        - POSTGRES_DB=database
        - POSTGRES_USER=morris
        - POSTGRES_PASSWORD=password
volumes:
    db:
networks: 
    default:
        name: api